/**
 * Everyday words a title never says ("Alkohol" → sucht). A wrong synonym
 * misroutes someone, so add a term only when the topic clearly owns it.
 */
export const topicSearchRelatedTerms: Record<string, string[]> = {
	'general-social-counselling': [
		'Sozialberatung',
		'Armut',
		'Bürgergeld',
		'Jobcenter',
		'Antrag',
		'Behörde',
		'Wohnung',
		'Miete',
		'wohnungslos',
		'obdachlos',
		'arbeitslos',
		'poverty',
		'benefits',
		'housing',
		'homeless',
		'unemployed'
	],
	'hospice-palliative-care-counselling': [
		'Hospiz',
		'palliativ',
		'Sterben',
		'Sterbebegleitung',
		'unheilbar',
		'Krebs',
		'schwer krank',
		'Lebensende',
		'dying',
		'terminal illness',
		'cancer',
		'end of life'
	],
	'life-in-old-age': [
		'Senioren',
		'Rente',
		'Pflege',
		'Pflegegrad',
		'Demenz',
		'Altenheim',
		'Einsamkeit im Alter',
		'elderly',
		'seniors',
		'pension',
		'dementia',
		'nursing care'
	],
	'trauerberatung': [
		'Trauer',
		'Tod',
		'Todesfall',
		'Verlust',
		'gestorben',
		'Beerdigung',
		'Sternenkind',
		'grief',
		'death',
		'loss',
		'bereavement',
		'funeral',
		'mourning'
	],
	'debt': [
		'Schulden',
		'Mahnung',
		'Inkasso',
		'Kredit',
		'Insolvenz',
		'Privatinsolvenz',
		'Pfändung',
		'Rechnungen',
		'Geldsorgen',
		'debt',
		'loan',
		'bills',
		'bankruptcy',
		'money problems'
	],
	'pregnancy': [
		'schwanger',
		'Baby',
		'Geburt',
		'Abtreibung',
		'Schwangerschaftsabbruch',
		'Schwangerschaftskonflikt',
		'ungewollt schwanger',
		'Verhütung',
		'Fehlgeburt',
		'Kinderwunsch',
		'pregnant',
		'abortion',
		'birth',
		'miscarriage',
		'contraception'
	],
	'offending': [
		'Gefängnis',
		'Haft',
		'JVA',
		'Knast',
		'Strafe',
		'Gericht',
		'Bewährung',
		'Haftentlassung',
		'Straftat',
		'prison',
		'jail',
		'probation',
		'court',
		'crime'
	],
	'sucht': [
		'Alkohol',
		'Drogen',
		'Kiffen',
		'Cannabis',
		'Spielsucht',
		'Glücksspiel',
		'Rauchen',
		'Medikamente',
		'Abhängigkeit',
		'Entzug',
		'Kokain',
		'Mediensucht',
		'addiction',
		'alcohol',
		'drugs',
		'gambling',
		'withdrawal'
	],
	'u25-suicide-prevention': [
		'Suizid',
		'Selbstmord',
		'Suizidgedanken',
		'nicht mehr leben',
		'sterben wollen',
		'Selbstverletzung',
		'Ritzen',
		'Verzweiflung',
		'hoffnungslos',
		'suicide',
		'suicidal',
		'self-harm',
		'cutting',
		'want to die',
		'hopeless'
	],
	'disability-psychological-impairment': [
		'Behinderung',
		'psychische Erkrankung',
		'Angststörung',
		'Psychose',
		'Rollstuhl',
		'Beeinträchtigung',
		'Inklusion',
		'Schwerbehindertenausweis',
		'disability',
		'mental illness',
		'anxiety',
		'wheelchair'
	],
	'hiv-aids': [
		'HIV',
		'Aids',
		'HIV-Test',
		'Geschlechtskrankheit',
		'STI',
		'Safer Sex',
		'PrEP',
		'sexually transmitted'
	],
	'cures-mothers-fathers': [
		'Kur',
		'Mutter-Kind-Kur',
		'Vater-Kind-Kur',
		'Mütterkur',
		'Erschöpfung',
		'Burnout',
		'Erholung',
		'exhaustion',
		'health retreat',
		'burnout'
	],
	'child-youth-rehabilitation': [
		'Reha',
		'Kinderreha',
		'chronisch krank',
		'Asthma',
		'Neurodermitis',
		'rehab',
		'chronic illness'
	],
	'children-youth-counselling': [
		'Schule',
		'Mobbing',
		'Pubertät',
		'Liebeskummer',
		'Streit mit Eltern',
		'Jugendliche',
		'teenager',
		'bullying',
		'youth'
	],
	'parents-and-family': [
		'Erziehung',
		'Trennung',
		'Scheidung',
		'alleinerziehend',
		'Sorgerecht',
		'Umgangsrecht',
		'Familienstreit',
		'parenting',
		'divorce',
		'separation',
		'single parent',
		'custody'
	],
	'counselling-men-boys': [
		'Männer',
		'Jungen',
		'Vater',
		'Männlichkeit',
		'Wut',
		'men',
		'boys',
		'father'
	],
	'school-to-work-transition': [
		'Ausbildung',
		'Beruf',
		'Bewerbung',
		'Praktikum',
		'Studium',
		'Schulabschluss',
		'Berufswahl',
		'Job',
		'apprenticeship',
		'career',
		'job application',
		'training'
	],
	'legal-guardianship-advance-care': [
		'rechtliche Betreuung',
		'Betreuer',
		'Vorsorgevollmacht',
		'Patientenverfügung',
		'Betreuungsverfügung',
		'Vollmacht',
		'legal guardianship',
		'power of attorney',
		'living will',
		'advance directive'
	],
	'initial-return-further-migration': [
		'Rückkehr',
		'Rückkehrberatung',
		'Heimkehr',
		'Weiterwanderung',
		'Ausreise',
		'Heimatland',
		'voluntary return',
		'return home',
		'onward migration'
	],
	'migration': [
		'Flucht',
		'geflüchtet',
		'Asyl',
		'Aufenthalt',
		'Aufenthaltstitel',
		'Visum',
		'Einbürgerung',
		'Integrationskurs',
		'Deutsch lernen',
		'Ausländerbehörde',
		'Familiennachzug',
		'refugee',
		'asylum',
		'residence permit',
		'visa',
		'immigration'
	]
};
