/* eslint-disable */
// Generated by scripts/generate-topic-search-catalog.mjs — do not edit.
// Source: registration.topic.catalog in src/resources/i18n/*/common.json

export type TopicSearchCatalogCopy = { title: string; description: string };

export const topicSearchCatalog: {
	topics: Record<string, Record<string, TopicSearchCatalogCopy>>;
} = {
	topics: {
		'child-youth-rehabilitation': {
			de: {
				title: 'Kinder- und Jugend-Reha',
				description:
					'Für junge Menschen, die nach Krankheit oder Belastung neue Kraft schöpfen möchten.'
			},
			en: {
				title: 'Pediatric Rehabilitation',
				description:
					'Rehabilitation guidance for children and young people.'
			},
			fr: {
				title: 'Rééducation pour enfants et adolescents',
				description:
					'Pour les jeunes qui souhaitent retrouver des forces après une maladie ou une épreuve.'
			},
			ru: {
				title: 'Реабилитация детей и подростков',
				description:
					'Для молодых людей, желающих восстановить силы после болезни или тяжёлой нагрузки.'
			},
			ti: {
				title: 'ናይ ቈልዑን መንእሰያትን ተሃድሶ',
				description: 'ድሕሪ ሕማም ወይ ጸቕጢ ሓድሽ ሓይሊ ክረኽቡ ንዝደልዩ መንእሰያት።'
			},
			tr: {
				title: 'Çocuk ve gençlik rehabilitasyonu',
				description:
					'Hastalık veya zorlanmadan sonra yeniden güç kazanmak isteyen gençler için.'
			}
		},
		'children-youth-counselling': {
			de: {
				title: 'Kinder und Jugendliche',
				description:
					'Wenn der Alltag zu viel wird - hier gibt es Hilfe und ein offenes Ohr.'
			},
			en: {
				title: 'Children and Young People',
				description:
					'Support and a listening ear when everyday life becomes too much.'
			},
			fr: {
				title: 'Enfants et adolescents',
				description:
					'Une écoute et un soutien quand le quotidien devient trop lourd.'
			},
			ru: {
				title: 'Дети и подростки',
				description:
					'Поддержка и внимательное отношение, когда повседневность становится непосильной.'
			},
			ti: {
				title: 'ቈልዑን መንእሰያትን',
				description: 'መዓልታዊ ናብራ ኣዝዩ ከቢድ ምስ ዝኸውን ደገፍን ሰማዒ እዝንን።'
			},
			tr: {
				title: 'Çocuklar ve gençler',
				description:
					'Günlük yaşam fazla geldiğinde burada yardım ve sizi dinleyen biri var.'
			}
		},
		'counselling-men-boys': {
			de: {
				title: 'Jungen- und Männerberatung',
				description:
					'Ein sicherer Raum für Männer und Jungen, um offen über Sorgen zu sprechen.'
			},
			en: {
				title: "Boys and Men's Support",
				description:
					'A safe space for men and boys to talk openly about worries.'
			},
			fr: {
				title: 'Conseil pour les garçons et les hommes',
				description:
					'Un espace sûr où les hommes et les garçons peuvent parler ouvertement de leurs soucis.'
			},
			ru: {
				title: 'Консультации для мальчиков и мужчин',
				description:
					'Безопасное пространство, где мужчины и мальчики могут открыто говорить о своих тревогах.'
			},
			ti: {
				title: 'ንኣወዳትን ደቂ ተባዕትዮን ዝኸውን ምኽሪ',
				description:
					'ደቂ ተባዕትዮን ኣወዳትን ብዛዕባ ጭንቀቶም ብግልጺ ክዛረቡሉ ዝኽእሉ ውሑስ ቦታ።'
			},
			tr: {
				title: 'Erkek çocuklar ve erkekler için danışmanlık',
				description:
					'Erkeklerin ve erkek çocukların endişelerini açıkça konuşabileceği güvenli bir alan.'
			}
		},
		'cures-mothers-fathers': {
			de: {
				title: 'Kuren für Mütter und Väter',
				description:
					'Kurmaßnahmen helfen erschöpften Eltern, wieder zu sich zu finden.'
			},
			en: {
				title: 'Parent Health Rehabilitation',
				description:
					'Guidance on recovery programs for exhausted parents.'
			},
			fr: {
				title: 'Cures pour mères et pères',
				description:
					'Les cures aident les parents épuisés à se retrouver.'
			},
			ru: {
				title: 'Оздоровительные программы для матерей и отцов',
				description:
					'Программы помогают истощённым родителям восстановить силы.'
			},
			ti: {
				title: 'ንኣዴታትን ኣቦታትን ዝኸውን ሕክምናዊ ዕረፍቲ',
				description: 'እዞም መደባት ንዝደኸሙ ወለዲ ሓይሎም ንኽመልሱ ይሕግዙ።'
			},
			tr: {
				title: 'Anneler ve babalar için kürler',
				description:
					'Yorgun ebeveynlerin yeniden güç toplamasına yardımcı olan kür programları hakkında danışmanlık.'
			}
		},
		'debt': {
			de: {
				title: 'Schulden',
				description:
					'Beratung bei finanziellen Sorgen, Mahnungen und Überschuldung.'
			},
			en: {
				title: 'Debt',
				description:
					'Counselling for financial worries, reminders, and over-indebtedness.'
			},
			fr: {
				title: 'Endettement',
				description:
					'Conseil en cas de soucis financiers, de rappels de paiement et de surendettement.'
			},
			ru: {
				title: 'Долги',
				description:
					'Консультации при финансовых трудностях, напоминаниях о долге и чрезмерной задолженности.'
			},
			ti: {
				title: 'ዕዳ',
				description: 'ኣብ ገንዘባዊ ጭንቀት፣ ናይ ክፍሊት መዘኻኸርን ልዑል ዕዳን ዝወሃብ ምኽሪ።'
			},
			tr: {
				title: 'Borç',
				description:
					'Maddi kaygılar, ihtarlar ve aşırı borçlanma konusunda danışmanlık.'
			}
		},
		'disability-psychological-impairment': {
			de: {
				title: 'Behinderung und psychische Beeinträchtigung',
				description:
					'Unterstuetzung bei Fragen zu Teilhabe, Alltag und Belastungen.'
			},
			en: {
				title: 'Disability and Mental Health Support',
				description:
					'Support for participation, everyday life, and psychological strain.'
			},
			fr: {
				title: 'Handicap et troubles psychiques',
				description:
					'Soutien pour les questions de participation, de quotidien et de charges psychiques.'
			},
			ru: {
				title: 'Инвалидность и психические нарушения',
				description:
					'Поддержка по вопросам участия, повседневной жизни и психологических нагрузок.'
			},
			ti: {
				title: 'ስንክልናን ኣእምሮኣዊ ጸገምን',
				description: 'ብዛዕባ ተሳትፎ፣ መዓልታዊ ናብራን ጸቕጥን ዝወሃብ ደገፍ።'
			},
			tr: {
				title: 'Engellilik ve psikolojik zorlanma',
				description:
					'Katılım, günlük yaşam ve psikolojik yüklerle ilgili sorularda destek.'
			}
		},
		'general-social-counselling': {
			de: {
				title: 'Allgemeine Sozialberatung',
				description:
					'Hilfe bei sozialen, finanziellen und persönlichen Fragen.'
			},
			en: {
				title: 'Social Support',
				description:
					'Help with social, financial, and personal questions.'
			},
			fr: {
				title: 'Conseil social général',
				description:
					'Aide pour les questions sociales, financières et personnelles.'
			},
			ru: {
				title: 'Общая социальная консультация',
				description:
					'Помощь по социальным, финансовым и личным вопросам.'
			},
			ti: {
				title: 'ሓፈሻዊ ማሕበራዊ ምኽሪ',
				description: 'ኣብ ማሕበራዊ፣ ገንዘባውን ውልቃውን ሕቶታት ዝወሃብ ሓገዝ።'
			},
			tr: {
				title: 'Genel sosyal danışmanlık',
				description: 'Sosyal, maddi ve kişisel sorularda yardım.'
			}
		},
		'hiv-aids': {
			de: {
				title: 'HIV und Aids',
				description:
					'Vertrauliche Beratung zu HIV, Aids, Gesundheit und Alltag.'
			},
			en: {
				title: 'HIV and AIDS',
				description:
					'Confidential counselling about HIV, AIDS, health, and everyday life.'
			},
			fr: {
				title: 'VIH et sida',
				description:
					'Conseil confidentiel sur le VIH, le sida, la santé et le quotidien.'
			},
			ru: {
				title: 'ВИЧ и СПИД',
				description:
					'Конфиденциальные консультации по вопросам ВИЧ, СПИДа, здоровья и повседневной жизни.'
			},
			ti: {
				title: 'ኤችኣይቪን ኤድስን',
				description: 'ብዛዕባ ኤችኣይቪ፣ ኤድስ፣ ጥዕናን መዓልታዊ ናብራን ዝወሃብ ምስጢራዊ ምኽሪ።'
			},
			tr: {
				title: 'HIV ve AIDS',
				description:
					'HIV, AIDS, sağlık ve günlük yaşam hakkında gizli danışmanlık.'
			}
		},
		'hospice-palliative-care-counselling': {
			de: {
				title: 'Hospiz- und Palliativberatung',
				description:
					'Beratung bei schwerer Krankheit, Sterben, Abschied und Begleitung.'
			},
			en: {
				title: 'Hospice and Palliative Care Support',
				description:
					'Counselling around serious illness, dying, farewell, and care.'
			},
			fr: {
				title: 'Conseil en soins palliatifs et hospice',
				description:
					"Conseil en cas de maladie grave, de fin de vie, d'adieu et d'accompagnement."
			},
			ru: {
				title: 'Хоспис и паллиативная помощь',
				description:
					'Консультации при тяжёлой болезни, умирании, прощании и сопровождении.'
			},
			ti: {
				title: 'ሆስፒስን ፓልያቲቭ ክንክንን ምኽሪ',
				description: 'ኣብ ከቢድ ሕማም፣ ሞት፣ ስንብታን ሓገዝን ዝወሃብ ምኽሪ።'
			},
			tr: {
				title: 'Hospis ve palyatif danışmanlık',
				description:
					'Ağır hastalık, ölüm, veda ve bakım süreçlerinde danışmanlık.'
			}
		},
		'initial-return-further-migration': {
			de: {
				title: 'Aus-/Rück- und Weiterwanderung',
				description:
					'Beratung zu Migration, Rückkehr und nächsten Schritten.'
			},
			en: {
				title: 'Relocation and Return Support',
				description:
					'Counselling on migration, return, and onward movement.'
			},
			fr: {
				title: 'Émigration, retour et migration ultérieure',
				description:
					'Conseil sur la migration, le retour et les étapes suivantes.'
			},
			ru: {
				title: 'Выезд, возвращение и дальнейшая миграция',
				description:
					'Консультации по вопросам миграции, возвращения и дальнейших шагов.'
			},
			ti: {
				title: 'ምውጻእ፣ ምምላስን ተወሳኺ ስደትን',
				description: 'ብዛዕባ ስደት፣ ምምላስን ዝቕጽሉ ስጉምትታትን ዝወሃብ ምኽሪ።'
			},
			tr: {
				title: 'Göç ve geri dönüş',
				description:
					'Göç, geri dönüş ve sonraki adımlar hakkında danışmanlık.'
			}
		},
		'legal-guardianship-advance-care': {
			de: {
				title: 'Rechtliche Betreuung und Vorsorge',
				description:
					'Orientierung zu Betreuung, Vollmacht und persönlicher Vorsorge.'
			},
			en: {
				title: 'Supported Decision-Making and Advance Planning',
				description:
					'Guidance on guardianship, powers of attorney, and advance care.'
			},
			fr: {
				title: 'Protection juridique et directives anticipées',
				description:
					'Orientation sur la curatelle, la procuration et les directives anticipées.'
			},
			ru: {
				title: 'Правовая опека и предварительные распоряжения',
				description:
					'Ориентация по вопросам опеки, доверенности и личных распоряжений.'
			},
			ti: {
				title: 'ሕጋዊ ሞግዚትነትን ኣቐዲምካ ምድላውን',
				description: 'ብዛዕባ ሞግዚትነት፣ ውክልናን ውልቃዊ ምድላውን ዝወሃብ መምርሒ።'
			},
			tr: {
				title: 'Yasal temsil ve önlem danışmanlığı',
				description:
					'Vesayet, vekaletname ve kişisel önlemler konusunda yönlendirme.'
			}
		},
		'life-in-old-age': {
			de: {
				title: 'Leben im Alter',
				description:
					'Unterstuetzung bei Fragen rund um Alter, Pflege und Alltag.'
			},
			en: {
				title: 'Later Life Support',
				description:
					'Support for questions around ageing, care, and everyday life.'
			},
			fr: {
				title: 'La vie à un âge avancé',
				description:
					"Soutien pour les questions liées à l'âge, aux soins et au quotidien."
			},
			ru: {
				title: 'Жизнь в пожилом возрасте',
				description:
					'Поддержка по вопросам старения, ухода и повседневной жизни.'
			},
			ti: {
				title: 'ናብራ ኣብ ግዜ እርጋን',
				description: 'ብዛዕባ እርጋን፣ ክንክንን መዓልታዊ ናብራን ዝምልከት ደገፍ።'
			},
			tr: {
				title: 'Yaşlılıkta yaşam',
				description:
					'Yaşlanma, bakım ve günlük yaşamla ilgili sorularda destek.'
			}
		},
		'migration': {
			de: {
				title: 'Migration',
				description:
					'Unterstützung bei Ankommen, Integration und Orientierung.'
			},
			en: {
				title: 'Migration Support',
				description:
					'Support with arrival, integration, and orientation.'
			},
			fr: {
				title: 'Migration',
				description:
					"Soutien à l'arrivée, à l'intégration et à l'orientation."
			},
			ru: {
				title: 'Миграция',
				description: 'Поддержка при прибытии, интеграции и ориентации.'
			},
			ti: {
				title: 'ስደት',
				description: 'ኣብ ምብጻሕ፣ ውህደትን ኣንፈት ምሃብን ዝወሃብ ደገፍ።'
			},
			tr: {
				title: 'Göç',
				description: 'Varış, entegrasyon ve yön bulma konusunda destek.'
			}
		},
		'offending': {
			de: {
				title: 'Straffälligkeit',
				description:
					'Begleitung bei Fragen zu Straffälligkeit, Neustart und Alltag.'
			},
			en: {
				title: 'Offender Support',
				description:
					'Support for questions around offending, restart, and daily life.'
			},
			fr: {
				title: 'Délinquance et réinsertion',
				description:
					'Accompagnement pour les questions de délinquance, de nouveau départ et de quotidien.'
			},
			ru: {
				title: 'Судимость',
				description:
					'Поддержка по вопросам правонарушений, нового начала и повседневной жизни.'
			},
			ti: {
				title: 'ገበንን ዳግመ ጅማሮን',
				description: 'ብዛዕባ ገበን፣ ሓድሽ ጅማሮን መዓልታዊ ናብራን ዝወሃብ ደገፍ።'
			},
			tr: {
				title: 'Suç ve yeniden başlangıç',
				description:
					'Suç, yeniden başlangıç ve günlük yaşamla ilgili sorularda destek.'
			}
		},
		'parents-and-family': {
			de: {
				title: 'Eltern und Familie',
				description:
					'Ob Erziehungsfragen, Konflikte oder familiäre Krisen - hier finden Sie verständnisvolle Begleitung.'
			},
			en: {
				title: 'Parent and Family Support',
				description:
					'Support for parenting questions, conflict, and family pressure.'
			},
			fr: {
				title: 'Parents et famille',
				description:
					"Questions d'éducation, conflits ou crises familiales : vous trouverez ici un accompagnement bienveillant."
			},
			ru: {
				title: 'Родители и семья',
				description:
					'Вопросы воспитания, конфликты или семейные кризисы — здесь вы найдёте понимающую поддержку.'
			},
			ti: {
				title: 'ወለድን ስድራቤትን',
				description:
					'ብዛዕባ ኣተዓባብያ፣ ግርጭት ወይ ስድራቤታዊ ቅልውላው ዝምልከት ሓጋዚ ደገፍ ኣብዚ ክትረኽቡ ኢኹም።'
			},
			tr: {
				title: 'Ebeveynler ve aile',
				description:
					'Ebeveynlik soruları, çatışmalar veya aile içi krizlerde anlayışlı destek bulabilirsiniz.'
			}
		},
		'pregnancy': {
			de: {
				title: 'Schwangerschaft',
				description:
					'Bei Fragen, Unsicherheit oder schwierigen Umständen sind wir da.'
			},
			en: {
				title: 'Pregnancy',
				description:
					'Support for pregnancy-related questions and difficult circumstances.'
			},
			fr: {
				title: 'Grossesse',
				description:
					"En cas de questions, d'incertitude ou de circonstances difficiles, nous sommes là."
			},
			ru: {
				title: 'Беременность',
				description:
					'Мы рядом, если у вас есть вопросы, сомнения или трудные обстоятельства.'
			},
			ti: {
				title: 'ጥንሲ',
				description:
					'ሕቶታት፣ ዘይንጹር ኩነታት ወይ ጽንኩር ኩነታት ምስ ዝህልወኩም ኣብ ጐንኹም ኣለና።'
			},
			tr: {
				title: 'Hamilelik',
				description:
					'Sorularınız, belirsizlikleriniz veya zor durumlarınız olduğunda yanınızdayız.'
			}
		},
		'school-to-work-transition': {
			de: {
				title: 'Übergang von Schule zu Beruf',
				description:
					'Begleitung beim Schritt von der Schule in Ausbildung, Studium und Beruf.'
			},
			en: {
				title: 'School-to-Work Transition',
				description:
					'Support for the step from school into training, study, and work.'
			},
			fr: {
				title: "Transition de l'école à la vie professionnelle",
				description:
					"Accompagnement lors du passage de l'école à la formation, aux études et à l'emploi."
			},
			ru: {
				title: 'От школы к профессии',
				description:
					'Поддержка при переходе от школы к профессиональному обучению, учёбе и работе.'
			},
			ti: {
				title: 'ካብ ትምህርቲ ናብ ሞያ ምስግጋር',
				description:
					'ካብ ቤት ትምህርቲ ናብ ሞያዊ ስልጠና፣ ላዕለዋይ ትምህርትን ስራሕን ኣብ ዝግበር ስግግር ደገፍ።'
			},
			tr: {
				title: 'Okuldan mesleğe geçiş',
				description:
					'Okuldan mesleki eğitime, üniversiteye ve iş hayatına geçişte destek.'
			}
		},
		'sucht': {
			de: {
				title: 'Sucht',
				description:
					'Beratung bei Suchtfragen, Abhängigkeit und belastenden Gewohnheiten.'
			},
			en: {
				title: 'Addiction',
				description:
					'Counselling for addiction questions, dependency, and harmful habits.'
			},
			fr: {
				title: 'Dépendances',
				description:
					"Conseil sur les questions d'addiction, de dépendance et d'habitudes pesantes."
			},
			ru: {
				title: 'Зависимость',
				description:
					'Консультации по вопросам зависимости и обременительных привычек.'
			},
			ti: {
				title: 'ወልፊ',
				description: 'ብዛዕባ ወልፊ፣ ጽግዕተኛነትን ከበድቲ ልምድታትን ዝወሃብ ምኽሪ።'
			},
			tr: {
				title: 'Bağımlılık',
				description:
					'Bağımlılık soruları, bağımlılık durumu ve zorlayıcı alışkanlıklar için danışmanlık.'
			}
		},
		'trauerberatung': {
			de: {
				title: 'Trauerberatung',
				description:
					'Begleitung bei Verlust, Abschied und schwerer Trauer.'
			},
			en: {
				title: 'Bereavement Support',
				description: 'Support with loss, farewell, and grief.'
			},
			fr: {
				title: 'Accompagnement du deuil',
				description:
					"Accompagnement en cas de perte, d'adieu et de deuil difficile."
			},
			ru: {
				title: 'Консультация в связи с утратой',
				description: 'Поддержка при утрате, прощании и тяжёлом горе.'
			},
			ti: {
				title: 'ናይ ሓዘን ምኽሪ',
				description: 'ኣብ ክሳራ፣ ስንብታን ከቢድ ሓዘንን ዝወሃብ ሓገዝ።'
			},
			tr: {
				title: 'Yas danışmanlığı',
				description: 'Kayıp, veda ve derin yas dönemlerinde destek.'
			}
		},
		'u25-suicide-prevention': {
			de: {
				title: '[U25] Suizidprävention',
				description:
					'Anonyme Begleitung für junge Menschen in Krisen und Suizidgedanken.'
			},
			en: {
				title: '[U25] Suicide Prevention',
				description:
					'Anonymous support for young people in crisis or with suicidal thoughts.'
			},
			fr: {
				title: '[U25] Prévention du suicide',
				description:
					'Accompagnement anonyme pour les jeunes en crise ou ayant des pensées suicidaires.'
			},
			ru: {
				title: '[U25] Профилактика суицида',
				description:
					'Анонимная поддержка молодых людей в кризисе или с суицидальными мыслями.'
			},
			ti: {
				title: '[U25] ካብ ነብሰ-ቕትለት ምክልኻል',
				description:
					'ኣብ ቅልውላው ንዘለዉ ወይ ናይ ነብሰ-ቕትለት ሓሳብ ንዘለዎም መንእሰያት ስውር ደገፍ።'
			},
			tr: {
				title: 'U25 intiharı önleme',
				description:
					'Kriz yaşayan veya intihar düşünceleri olan gençler için anonim destek.'
			}
		}
	}
};
