// @vitest-environment jsdom
/**
 * Golden fixture for tenant seed colours (ORISO-UserService#1252, ADR-026
 * amendment 2026-10-02).
 *
 * `__fixtures__/tenant-colour-golden.json` is OWNED BY THIS REPOSITORY. It
 * records what the real `applyTenantPalette` does with a tenant's
 * `primaryColor`: is the seed accepted, which `--m3-primary` /
 * `--m3-on-primary` / `--m3-primary-hover` result. ORISO-UserService keeps
 * a byte-identical copy and renders mails against it, so mail and web app
 * accept and reject the same colours and derive the same button label.
 *
 * Never edit the JSON by hand. After an intended change of the theme
 * engine, regenerate it and commit it together with the engine change:
 *
 *   UPDATE_TENANT_COLOUR_GOLDEN=1 npx vitest run --project unit \
 *     src/utils/theme/tenantColourGolden.test.ts
 *
 * Then copy the file to ORISO-UserService
 * (src/test/resources/email/tenant-colour-golden.json) in a PR there.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { applyTenantPalette } from './applyTenantTheme';

const FIXTURE = path.join(
	__dirname,
	'__fixtures__',
	'tenant-colour-golden.json'
);

/** Seeds as a tenant record could carry them; null means "not stored". */
const SEEDS: Array<string | null> = [
	'#1c4f8f', // dark blue: white label
	'#a5000a', // ORISO red
	'#f8e71c', // light yellow: dark label
	'#ffff00',
	'#ffd400',
	'#1C4F8F', // upper case
	'#1c4f8f ', // trailing blank
	'#fc0', // 3-digit shorthand
	'#808080', // grey: too pale
	'#8a8a8a', // grey: too pale
	'#000000', // black: too pale
	'#ffffff', // white: too pale
	'#d32f2f', // around 4.5:1 against white
	'#da3532', // 4.63:1, just above the white-label threshold
	'#dc3a35', // 4.47:1, just below
	'#b04ac0', // 4.58:1, just above
	'#b34cc4', // 4.42:1, just below
	'#e53935',
	'#1e88e5',
	'#00897b',
	'#43a047',
	'#7b1fa2',
	'not-a-colour',
	'#12345',
	'',
	'   ',
	null
];

interface GoldenCase {
	seed: string | null;
	accepted: boolean;
	primary: string | null;
	onPrimary: string | null;
	labelIsWhite: boolean | null;
	primaryHover: string | null;
}

const compute = (seed: string | null | undefined): GoldenCase => {
	const root = document.createElement('div');
	vi.spyOn(console, 'warn').mockImplementation(() => undefined);
	const accepted = applyTenantPalette({ primaryColor: seed }, root);
	vi.restoreAllMocks();
	if (!accepted) {
		return {
			seed: seed ?? null,
			accepted: false,
			primary: null,
			onPrimary: null,
			labelIsWhite: null,
			primaryHover: null
		};
	}
	const get = (name: string) => root.style.getPropertyValue(name);
	const onPrimary = get('--m3-on-primary');
	return {
		seed: seed ?? null,
		accepted: true,
		primary: get('--m3-primary'),
		onPrimary,
		labelIsWhite: onPrimary === '#ffffff',
		primaryHover: get('--m3-primary-hover')
	};
};

const generate = () => ({
	description:
		'Owned by ORISO-Frontend (src/utils/theme/__fixtures__/tenant-colour-golden.json). ' +
		'Generated by tenantColourGolden.test.ts from the real applyTenantPalette; do not edit by hand.',
	engine: 'applyTenantPalette / computeOrisoPalette(light), @material/material-color-utilities',
	cases: SEEDS.map(compute)
});

describe('tenant colour golden fixture', () => {
	it('matches the output of the real theme engine', () => {
		const expected = generate();
		if (process.env.UPDATE_TENANT_COLOUR_GOLDEN === '1') {
			writeFileSync(FIXTURE, `${JSON.stringify(expected, null, '\t')}\n`);
		}
		const onDisk = JSON.parse(readFileSync(FIXTURE, 'utf8'));
		expect(onDisk).toEqual(expected);
	});

	it('covers accepted and rejected seeds, white and dark labels', () => {
		const { cases } = JSON.parse(readFileSync(FIXTURE, 'utf8')) as {
			cases: GoldenCase[];
		};
		expect(cases.some((c) => c.accepted && c.labelIsWhite)).toBe(true);
		expect(cases.some((c) => c.accepted && c.labelIsWhite === false)).toBe(
			true
		);
		expect(cases.some((c) => !c.accepted)).toBe(true);
	});
});
